{{ config(materialized='view') }}

select
    "ID"::text as claim_transaction_id,
    "CLAIMID"::text as claim_id,
    "CHARGEID"::text as charge_id,
    "PATIENTID"::text as patient_id,
    "TYPE"::text as claim_type,
    nullif("AMOUNT", '')::numeric as transaction_amount,
    "METHOD"::text as transaction_method,
    nullif("FROMDATE", '')::date as service_from_date,
    nullif("TODATE", '')::date as service_to_date,
    "PLACEOFSERVICE"::text as place_of_service,
    "PROCEDURECODE"::text as procedure_code,
    "MODIFIER1"::text as modifier_1,
    "MODIFIER2"::text as modifier_2,
    "DIAGNOSISREF1"::text as diagnosis_ref_1,
    "DIAGNOSISREF2"::text as diagnosis_ref_2,
    "DIAGNOSISREF3"::text as diagnosis_ref_3,
    "DIAGNOSISREF4"::text as diagnosis_ref_4,
    nullif("UNITS", '')::numeric as unit_count,
    "DEPARTMENTID"::text as department_id,
    "NOTES"::text as notes,
    nullif("UNITAMOUNT", '')::numeric as unit_amount,
    "TRANSFEROUTID"::text as transfer_out_id,
    "TRANSFERTYPE"::text as transfer_type,
    nullif("PAYMENTS", '')::numeric as payment_amount,
    nullif("ADJUSTMENTS", '')::numeric as adjustment_amount,
    nullif("TRANSFERS", '')::numeric as transfer_amount,
    nullif("OUTSTANDING", '')::numeric as outstanding_amount,
    "APPOINTMENTID"::text as appointment_id,
    "LINENOTE"::text as line_note,
    "PATIENTINSURANCEID"::text as patient_insurance_id,
    "FEESCHEDULEID"::text as fee_schedule_id,
    "PROVIDERID"::text as provider_id,
    "SUPERVISINGPROVIDERID"::text as supervising_provider_id,
    date_trunc('month', nullif("FROMDATE", '')::date)::date as service_month,
    case when coalesce(nullif("PAYMENTS", '')::numeric, 0) > 0 then true else false end as is_paid_claim_line,
    case when coalesce(nullif("OUTSTANDING", '')::numeric, 0) > 0 then true else false end as is_outstanding_claim_line
from {{ source('synthea', 'claims_transactions') }}