{{ config(materialized='view') }}

select
    "Id"::text as patient_id,
    nullif("BIRTHDATE", '')::date as birth_date,
    nullif("DEATHDATE", '')::date as death_date,
    "SSN"::text as ssn,
    "DRIVERS"::text as drivers_license_number,
    "PASSPORT"::text as passport_number,
    "PREFIX"::text as name_prefix,
    "FIRST"::text as first_name,
    "MIDDLE"::text as middle_name,
    "LAST"::text as last_name,
    "SUFFIX"::text as name_suffix,
    "MAIDEN"::text as maiden_name,
    "MARITAL"::text as marital_status,
    "RACE"::text as race,
    "ETHNICITY"::text as ethnicity,
    "GENDER"::text as gender,
    "BIRTHPLACE"::text as birthplace,
    "ADDRESS"::text as address,
    "CITY"::text as city,
    "STATE"::text as state,
    "COUNTY"::text as county,
    "FIPS"::text as fips_code,
    "ZIP"::text as zip_code,
    nullif("LAT", '')::numeric as latitude,
    nullif("LON", '')::numeric as longitude,
    nullif("HEALTHCARE_EXPENSES", '')::numeric as healthcare_expenses,
    nullif("HEALTHCARE_COVERAGE", '')::numeric as healthcare_coverage,
    nullif("INCOME", '')::numeric as income,
    concat_ws(' ', "FIRST", "MIDDLE", "LAST") as patient_full_name,
    case when nullif("DEATHDATE", '') is not null then true else false end as is_deceased,
    extract(year from age(current_date, nullif("BIRTHDATE", '')::date))::int as current_age
from {{ source('synthea', 'patients') }}