FROM python:3.11-slim

# install git + basic build tools
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# install dbt
RUN pip install --no-cache-dir dbt-core dbt-postgres

# create user
RUN useradd -ms /bin/bash dbtuser

USER dbtuser
WORKDIR /workspace